### ISSUE TITLE
CPU pegged on opening package.json.

### ISSUE THREAD

**Issue by phyllisstein** [kilian-ito/atom-npm-outdated#11]
I'm having a little trouble with this package all of a sudden: opening `package.json` pegs my CPU, locking up Atom and most of the rest of the machine till I can force-kill the process:

<img width="326" alt="screen shot 2018-07-07 at 7 22 17 pm" src="https://user-images.githubusercontent.com/2207980/42415442-8f8a0f80-821c-11e8-8b35-56387847c0a3.png">

I'm not totally certain what's causing it, but a little digging in the dev tools suggests that it might have started with this commit: https://github.com/kilian-ito/atom-npm-outdated/commit/87d9840b2c4c6e2a8bc0740950859475525cad15. I think something in the new logic is choking on TypeScript's versions, specifically---it has over 1,000 individual version numbers in NPM:

<img width="544" alt="screen shot 2018-07-07 at 7 31 01 pm" src="https://user-images.githubusercontent.com/2207980/42415448-c9dff938-821c-11e8-9c8b-0920ce08a1b2.png">

The standard whine is that it worked fine before, but I appreciate the wish to move the core of the package forward. Is there maybe some way to handle edge cases like this more gracefully without totally discarding the changes in 87d9840b2c4c6e2a8bc0740950859475525cad15?

Thanks so much for considering it, I appreciate the effort!

**Comment by kilian-ito** [comment]
Hello @phyllisstein ,

thank you for the report.
This issue appear because I have delegated the request to ne NPM CLI (in a child process).
I am working to a way to re-integrate the request in the code.

**Comment by kilian-ito** [comment]
I have implemented a workaround in the version 0.16.0.
The number of parallel calls is reduced to 10 (and is configurable).

This is not the best solution but it will fix.

**Comment by phyllisstein** [comment]
That's great! Thanks so much.

**Comment by phyllisstein** [comment]
This package has been working great for me again as of the last few updates. I had to throttle the number of parallel requests down to 3, otherwise lint errors in `package.json` never appeared and Atom started to choke (which on a six-month-old MacBook Pro is a little odd), but after doing that everything's hunky-dory. Probably safe to close this now!

**Comment by kilian-ito** [comment]
Hi @phyllisstein ,
I was waiting to have the progressive reporting feature to close this issue.
The next step (in another feature) will be to generate the HTTP call inside the package instead of using the NPM client in child process to reduce the reduce the RAM needed.

If you still have issue feel free to re-open this issue report.

regards
