### ISSUE TITLE
Honor .npmrc registry & auth

### ISSUE THREAD

**Issue by jsg2021** [kilian-ito/atom-npm-outdated#7]
It would be awesome to honor `~/.npmrc`'s `registry=` & `@scope:registry=` settings as well as the registry auths, since some private registries can't be read w/o auth. 

I may be able to submit a PR, but don't wait on me if you can/want to jump on this. :)

**Comment by kilian-ito** [comment]
Hi @jsg2021 ,
Thank you for the report.

I have added the feature on version 0.14.0

**Comment by jsg2021** [comment]
Awesome, thanks!

Is there a cache? I think npm is getting thrashed as i hover or modify the file.

**Comment by kilian-ito** [comment]
There is a cache mecanism but it was not adapted to the new version to retreive package info.
I have updated it in the 0.15.0

**Comment by jsg2021** [comment]
W00t! thanks!
